# 端口
server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: cloud-eureka-server

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: 127.0.0.1
  client:
    # 是否将自己注册到Eureka服务中,因为该应用本身就是注册中心，不需要再注册自己（集群的时候为true）
    register-with-eureka: false
    # 表示自己端就是注册中心，职责就是维护服务实例，并不需要去检查服务
    fetch-registry: true
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
#  server:
#    enable-self-preservation: false
