server:
  port: 8087
  enable-self-preservation: false

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/ls199802/springcloud   #git仓库地址
          searchPaths: spring-cloud-config-file
          label: master              #默认分支
          username:                  #公开仓库不需要账号密码
          password:


eureka:
  instance:
    #注册中心地址
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/