
# 端口
server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: eureka-client

# Eureka配置
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: localhost
  client:
    # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
